 SELECT MAX(E.SAL) AS MAX_SAL,SUM(E.SAL) AS TOTAL_SAL,D.DNAME AS DEPARTMENT_NAME
 FROM EMP E INNER JOIN DEPT D
 ON E.DEPTNO = D.DEPTNO
 WHERE E.DEPTNO IN (SELECT DEPTNO
             FROM EMP
             WHERE LOC IN ('CHICAGO','DALLAS'))
 AND E.SAL*12 > (SELECT SAL * 12
          FROM EMP
          WHERE ENAME='SMITH')
 AND E.HIREDATE < (SELECT HIREDATE
            FROM EMP
            WHERE ENAME='MILLER')
 GROUP BY D.DNAME
 HAVING SUM(E.SAL) > ALL (SELECT SAL
               FROM EMP
               WHERE JOB ='CLERK')
/
