 SELECT E.EMPNO,E.ENAME,
 M.ENAME,
 MD.DNAME,SUBSTR(MMD.LOC,1,2)
 FROM EMP E JOIN EMP M
 ON E.MGR = M.EMPNO
 JOIN EMP MM
 ON M.MGR = MM.EMPNO
 JOIN DEPT MD
 ON M.DEPTNO = MD.DEPTNO
 JOIN DEPT MMD
 ON MM.DEPTNO = MMD.DEPTNO
 WHERE E.JOB IN ('ANALYST','SALESMAN','CLERK')
 AND E.SAL < (SELECT SAL
       FROM (SELECT DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK,SAL
      FROM EMP)
       WHERE RANK = 8)
 AND M.HIREDATE > (SELECT HIREDATE
     FROM EMP
     WHERE ENAME='SMITH')
 AND (INSTR(MM.ENAME,'A',1,1) > 0
 OR INSTR(MM.ENAME,'K',1,1) > 0
 OR INSTR(MM.ENAME,'M',1,1) > 0
 OR INSTR(MM.ENAME,'O',1,1) > 0)
 AND MMD.LOC IN ('NEW YORK','DALLAS','CHICAGO')
/
