SELECT *
FROM (SELECT DENSE_RANK() OVER (ORDER BY SAL ASC) AS RANK,EMPNO,ENAME,TO_CHAR(HIREDATE,'FMDAY'),TO_CHAR(HIREDATE,'HH24'),DNAME
FROM EMP E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
)
WHERE RANK IN (2,4,5,6,7)
/
